# Site settings
title: GSHS TeX Society
baseurl: ""
url: "http://gshstexsociety.github.io"

# Build settings
markdown: kramdown
# enable recognition of Github Flavored Markdown (GFM)
# kramdown:
#  input: GFM

# Permalinks
# http://jekyllrb.com/docs/permalinks/
# permalink: date|pretty|ordinal|none
permalink: pretty

# GitHub:
github:
  repo: gshstexsociety/gshstexsociety.github.io
  branch: master
